-- begin SAMPLE_PLANIN_CLIENT_LINK
alter table SAMPLE_PLANIN_CLIENT_LINK add constraint FK_SAMPLACLI_ON_PLANIN foreign key (PLANIN_ID) references EXCEEDTEST_PLANIN(ID)^
alter table SAMPLE_PLANIN_CLIENT_LINK add constraint FK_SAMPLACLI_ON_CLIENT foreign key (CLIENT_ID) references EXCEEDTEST_CLIENT(ID)^
-- end SAMPLE_PLANIN_CLIENT_LINK
-- begin EXCEEDTEST_CLIENT
create unique index IDX_EXCEEDTEST_CLIENT_UNQ on EXCEEDTEST_CLIENT (CLIENT_CODE) where DELETE_TS is null ^
-- end EXCEEDTEST_CLIENT
-- begin EXCEEDTEST_GATE
create unique index IDX_EXCEEDTEST_GATE_UNQ on EXCEEDTEST_GATE (GATE_NUMBER) where DELETE_TS is null ^
-- end EXCEEDTEST_GATE
-- begin EXCEETEST_APP_SETTING
create unique index IDX_EXCEETEST_APP_SETTING_UK_NAME on EXCEETEST_APP_SETTING (NAME) where DELETE_TS is null ^
-- end EXCEETEST_APP_SETTING
